Repository letiendat1002/e-commerce, pull requests merged in 2023-04, with the labels that each got.

#33 [Feature] [User] Sort Product
  frontend/src/pages/Client/Menu.jsx
  frontend/src/routes/index.js
Labels: enhancement

#39 construct directory and update database
  .gitignore
  assets/database/mysql/dbs_model.mwb
  assets/database/mysql/dbs_model.mwb.bak
  assets/database/mysql/dbs_model.sql
  backend/.gitignore
  backend/.idea/.gitignore
  backend/.mvn/wrapper/maven-wrapper.jar
  backend/.mvn/wrapper/maven-wrapper.properties
  backend/README.md
  backend/docs/README.md
  backend/mvnw
  backend/mvnw.cmd
  backend/pom.xml
  backend/src/main/java/com/ecommerce/backend/BackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/ecommerce/backend/BackendApplicationTests.java
Labels: enhancement

#41 Code scanning configuration
  .github/workflows/codeql.yml
Labels: task

#43 Update codeql.yml
  .github/workflows/codeql.yml
Labels: bug
