Repository letiendat1002/e-commerce, pull requests merged in 2023-05, with the labels that each got.

#56 Cart page update
  frontend/package.json
  frontend/src/Helper/GetProduct.js
  frontend/src/Redux/api/productController.js
  frontend/src/Redux/slice/cartSlice.js
  frontend/src/Redux/slice/categorySlice.js
  frontend/src/Redux/slice/productSlice.js
  frontend/src/Redux/store.js
  frontend/src/assets/css/cart.scss
  frontend/src/assets/css/home.scss
  frontend/src/assets/css/menu.scss
  frontend/src/assets/css/product-detail.scss
  frontend/src/assets/data/product.js
  frontend/src/assets/images/74/637546117379617339_imac-24-silver-1.jpg
  frontend/src/assets/images/74/637846093546558931_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (1).jpg
  frontend/src/assets/images/74/637846093546715146_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (2).jpg
  frontend/src/assets/images/74/637846093546715146_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (4).jpg
  frontend/src/assets/images/74/637846093546871494_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (3).jpg
  frontend/src/assets/images/74/637846093548121524_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (7).jpg
  frontend/src/assets/images/74/637846093548746496_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (8).jpg
  frontend/src/assets/images/74/637846093549371523_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (6).jpg
  frontend/src/assets/images/75/637546117379617339_imac-24-silver-1.jpg
  frontend/src/assets/images/75/637846093546558931_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (1).jpg
  frontend/src/assets/images/75/637846093546715146_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (2).jpg
  frontend/src/assets/images/75/637846093546715146_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (4).jpg
  frontend/src/assets/images/75/637846093546871494_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (3).jpg
  frontend/src/assets/images/75/637846093548121524_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (7).jpg
  frontend/src/assets/images/75/637846093548746496_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (8).jpg
  frontend/src/assets/images/75/637846093549371523_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (6).jpg
  frontend/src/assets/images/76/637546117379617339_imac-24-silver-1.jpg
  frontend/src/assets/images/76/637846093546558931_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (1).jpg
  frontend/src/assets/images/76/637846093546715146_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (2).jpg
  frontend/src/assets/images/76/637846093546715146_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (4).jpg
  frontend/src/assets/images/76/637846093546871494_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (3).jpg
  frontend/src/assets/images/76/637846093548121524_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (7).jpg
  frontend/src/assets/images/76/637846093548746496_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (8).jpg
  frontend/src/assets/images/76/637846093549371523_iMac 24 2021 Retina 45K M18-Core CPU7-Core GPU8GB256GB SSD (6).jpg
  frontend/src/components/Table/index.jsx
  frontend/src/components/Table/style.scss
  frontend/src/pages/Client/Cart.jsx
  frontend/src/pages/Client/Home.jsx
  frontend/src/pages/Client/Menu.jsx
  frontend/src/pages/Client/Payment.jsx
  frontend/src/pages/Client/ProductDetail.jsx
Labels: enhancement

#65 Hotfix cors jwt
  backend/assets/images/security/authenticate.png
  backend/docs/APIs.md
  backend/src/main/java/com/ecommerce/backend/shared/security/CorsConfig.java
  backend/src/main/java/com/ecommerce/backend/shared/security/jwt/JwtService.java
Labels: bugfix

#67 Order API
  backend/README.md
  backend/assets/databases/mysql/dbs_model.mwb
  backend/assets/databases/mysql/dbs_model.mwb.bak
  backend/assets/databases/mysql/dbs_model.sql
  backend/docs/RolePermission.md
  backend/src/main/java/com/ecommerce/backend/order/Order.java
  backend/src/main/java/com/ecommerce/backend/order/OrderAddRequest.java
  backend/src/main/java/com/ecommerce/backend/order/OrderController.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDAO.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDTO.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDTOMapper.java
  backend/src/main/java/com/ecommerce/backend/order/OrderJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/order/OrderRepository.java
  backend/src/main/java/com/ecommerce/backend/order/OrderResponse.java
  backend/src/main/java/com/ecommerce/backend/order/OrderService.java
  backend/src/main/java/com/ecommerce/backend/order/OrderServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/order/OrderUpdateRequest.java
  backend/src/main/java/com/ecommerce/backend/order/enums/OrderPaymentType.java
  backend/src/main/java/com/ecommerce/backend/order/enums/OrderStatus.java
  backend/src/main/java/com/ecommerce/backend/product/ProductController.java
  backend/src/main/java/com/ecommerce/backend/shared/exception/handler/DefaultExceptionHandler.java
  backend/src/main/java/com/ecommerce/backend/shared/security/jwt/JwtService.java
  backend/src/main/java/com/ecommerce/backend/user/User.java
  backend/src/main/java/com/ecommerce/backend/user/enums/UserRole.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressController.java
Labels: documentation, enhancement

#70 allow no authorize for get all products and categories
  backend/src/main/java/com/ecommerce/backend/category/CategoryController.java
  backend/src/main/java/com/ecommerce/backend/product/ProductController.java
  backend/src/main/java/com/ecommerce/backend/shared/security/SecurityConfig.java
Labels: bugfix

#71 Order Detail API
  backend/assets/databases/mysql/dbs_model.mwb
  backend/assets/databases/mysql/dbs_model.mwb.bak
  backend/assets/databases/mysql/dbs_model.sql
  backend/docs/RolePermission.md
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationRequest.java
  backend/src/main/java/com/ecommerce/backend/category/CategoryController.java
  backend/src/main/java/com/ecommerce/backend/category/CategoryRequest.java
  backend/src/main/java/com/ecommerce/backend/order/Order.java
  backend/src/main/java/com/ecommerce/backend/order/OrderAddRequest.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDTO.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDTOMapper.java
  backend/src/main/java/com/ecommerce/backend/order/OrderServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/order/OrderUpdateRequest.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetail.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailController.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailDAO.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailDTO.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailDTOMapper.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailID.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailRepository.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailRequest.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailResponse.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailService.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/product/Product.java
  backend/src/main/java/com/ecommerce/backend/product/ProductController.java
  backend/src/main/java/com/ecommerce/backend/product/ProductRequest.java
  backend/src/main/java/com/ecommerce/backend/shared/exception/handler/DefaultExceptionHandler.java
  backend/src/main/java/com/ecommerce/backend/shared/security/SecurityConfig.java
  backend/src/main/java/com/ecommerce/backend/user/UserRegistrationRequest.java
  backend/src/main/java/com/ecommerce/backend/user/UserServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/user/UserUpdateRequest.java
  backend/src/main/java/com/ecommerce/backend/user/enums/UserRole.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddress.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressRequest.java
Labels: documentation, enhancement

#74 Handle transaction cascade user-order-orderdetail
  backend/src/main/java/com/ecommerce/backend/order/OrderServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailController.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/user/UserServiceImpl.java
Labels: enhancement, optimize

#83 Email Verification
  backend/assets/databases/mysql/dbs_model.mwb
  backend/assets/databases/mysql/dbs_model.mwb.bak
  backend/assets/databases/mysql/dbs_model.sql
  backend/assets/databases/mysql/test_query.sql
  backend/docs/RolePermission.md
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationAuthenticateResponse.java
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationController.java
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationRegisterResponse.java
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationService.java
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/order/OrderServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/rating/RatingController.java
  backend/src/main/java/com/ecommerce/backend/shared/config/OpenApiConfig.java
  backend/src/main/java/com/ecommerce/backend/shared/config/SpringAsyncConfig.java
  backend/src/main/java/com/ecommerce/backend/shared/constants/VariableConstants.java
  backend/src/main/java/com/ecommerce/backend/shared/email/CustomEmail.java
  backend/src/main/java/com/ecommerce/backend/shared/email/EmailSenderService.java
  backend/src/main/java/com/ecommerce/backend/shared/email/EmailTemplate.java
  backend/src/main/java/com/ecommerce/backend/shared/exception/JwtAuthenticationException.java
  backend/src/main/java/com/ecommerce/backend/shared/exception/handler/DefaultExceptionHandler.java
  backend/src/main/java/com/ecommerce/backend/shared/runner/CommandLineAppStartupRunner.java
  backend/src/main/java/com/ecommerce/backend/shared/security/CorsConfig.java
  backend/src/main/java/com/ecommerce/backend/shared/security/SecurityConfig.java
  backend/src/main/java/com/ecommerce/backend/shared/security/jwt/JwtService.java
  backend/src/main/java/com/ecommerce/backend/user/User.java
  backend/src/main/java/com/ecommerce/backend/user/UserDAO.java
  backend/src/main/java/com/ecommerce/backend/user/UserDTO.java
  backend/src/main/java/com/ecommerce/backend/user/UserDTOMapper.java
  backend/src/main/java/com/ecommerce/backend/user/UserJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/user/UserRepository.java
  backend/src/main/java/com/ecommerce/backend/user/UserService.java
  backend/src/main/java/com/ecommerce/backend/user/UserServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/user/enums/EmailValidationStatus.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
Labels: documentation, enhancement

#85 Reset Password + Change Password
  backend/docs/RolePermission.md
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationChangePasswordRequest.java
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationController.java
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationService.java
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/shared/email/EmailTemplate.java
  backend/src/main/java/com/ecommerce/backend/shared/exception/PasswordException.java
  backend/src/main/java/com/ecommerce/backend/shared/exception/handler/DefaultExceptionHandler.java
  backend/src/main/java/com/ecommerce/backend/shared/security/SecurityConfig.java
  backend/src/main/java/com/ecommerce/backend/user/UserDAO.java
  backend/src/main/java/com/ecommerce/backend/user/UserJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/user/UserRepository.java
  backend/src/main/java/com/ecommerce/backend/user/UserService.java
  backend/src/main/java/com/ecommerce/backend/user/UserServiceImpl.java
Labels: documentation, enhancement

#89 Allow no email verification to login
  backend/src/main/java/com/ecommerce/backend/shared/email/EmailSenderService.java
  backend/src/main/java/com/ecommerce/backend/user/User.java
  backend/src/test/java/com/ecommerce/backend/MainTests.java
  backend/src/test/java/com/ecommerce/backend/util/TestConfig.java
  backend/src/test/java/com/ecommerce/backend/util/TestConstants.java
Labels: bugfix

#91 handle old new password
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationServiceImpl.java
  backend/src/test/java/com/ecommerce/backend/util/TestConfig.java
Labels: bugfix

#108 hotfix-refund
  backend/docs/RolePermission.md
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailServiceImpl.java
Labels: bugfix

#113 Resolve price
  frontend/src/pages/Admin/components/ModalViewOrder/ModelViewOrder.jsx
  frontend/src/pages/Admin/components/ModelViewRefund/ModelViewRefund.jsx
Labels: update, bugfix

#117 Testing service
  backend/README.md
  backend/assets/images/database/database_design.png
  backend/assets/images/database/database_info_v1.png
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/auth/enums/ActivateStatus.java
  backend/src/main/java/com/ecommerce/backend/order/Order.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDAO.java
  backend/src/main/java/com/ecommerce/backend/order/OrderJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/order/OrderServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/product/ProductService.java
  backend/src/main/java/com/ecommerce/backend/product/ProductServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/rating/Rating.java
  backend/src/main/java/com/ecommerce/backend/rating/RatingServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/shared/email/EmailTemplate.java
  backend/src/main/java/com/ecommerce/backend/user/enums/Gender.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddress.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressAddRequest.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressController.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressDAO.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressDTOMapper.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressRepository.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressService.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressUpdateRequest.java
  backend/src/test/java/com/ecommerce/backend/auth/AuthenticationServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/category/CategoryServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/controller/AuthenticationControllerTest.java
  backend/src/test/java/com/ecommerce/backend/controller/CategoryControllerTest.java
  backend/src/test/java/com/ecommerce/backend/controller/OrderControllerTest.java
  backend/src/test/java/com/ecommerce/backend/controller/OrderDetailControllerTest.java
  backend/src/test/java/com/ecommerce/backend/controller/ProductControllerTest.java
  backend/src/test/java/com/ecommerce/backend/controller/RatingControllerTest.java
  backend/src/test/java/com/ecommerce/backend/controller/UserAddressControllerTest.java
  backend/src/test/java/com/ecommerce/backend/controller/UserControllerTest.java
  backend/src/test/java/com/ecommerce/backend/integration/MainIT.java
  backend/src/test/java/com/ecommerce/backend/integration/MainTests.java
  backend/src/test/java/com/ecommerce/backend/order/OrderServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/orderdetail/OrderDetailServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/product/ProductServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/rating/RatingServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/AuthenticationServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/OrderDetailServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/ProductServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/RatingServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/UserAddressServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/user/UserServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/useraddress/UserAddressServiceImplTest.java
Labels: documentation, update, optimize, testing

#118 Shipping api
  backend/assets/databases/mysql/dbs_model.mwb
  backend/assets/databases/mysql/dbs_model.mwb.bak
  backend/assets/databases/mysql/dbs_model.sql
  backend/src/main/java/com/ecommerce/backend/auth/AuthenticationController.java
  backend/src/main/java/com/ecommerce/backend/category/CategoryController.java
  backend/src/main/java/com/ecommerce/backend/order/Order.java
  backend/src/main/java/com/ecommerce/backend/order/OrderController.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDAO.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDTO.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDTOMapper.java
  backend/src/main/java/com/ecommerce/backend/order/OrderJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/order/OrderRepository.java
  backend/src/main/java/com/ecommerce/backend/order/OrderService.java
  backend/src/main/java/com/ecommerce/backend/order/OrderServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/order/OrderStatisticResponse.java
  backend/src/main/java/com/ecommerce/backend/order/OrderUpdateRequest.java
  backend/src/main/java/com/ecommerce/backend/order/enums/OrderStatus.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailController.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailService.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/product/ProductController.java
  backend/src/main/java/com/ecommerce/backend/rating/RatingController.java
  backend/src/main/java/com/ecommerce/backend/shared/runner/CommandLineAppStartupRunner.java
  backend/src/main/java/com/ecommerce/backend/shared/security/enums/UserPermission.java
  backend/src/main/java/com/ecommerce/backend/shared/security/enums/UserRole.java
  backend/src/main/java/com/ecommerce/backend/user/User.java
  backend/src/main/java/com/ecommerce/backend/user/UserController.java
  backend/src/main/java/com/ecommerce/backend/user/UserDAO.java
  backend/src/main/java/com/ecommerce/backend/user/UserJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/user/UserRepository.java
  backend/src/main/java/com/ecommerce/backend/user/UserService.java
  backend/src/main/java/com/ecommerce/backend/user/UserServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/user/UserUpdateRequest.java
  backend/src/main/java/com/ecommerce/backend/user/enums/UserPermission.java
  backend/src/main/java/com/ecommerce/backend/user/enums/UserRole.java
  backend/src/main/java/com/ecommerce/backend/useraddress/UserAddressController.java
  backend/src/test/java/com/ecommerce/backend/unit/auth/AuthenticationServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/unit/category/CategoryServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/unit/order/OrderServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/unit/orderdetail/OrderDetailServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/unit/product/ProductServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/unit/rating/RatingServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/unit/user/UserServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/unit/useraddress/UserAddressServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/user/UserServiceImplTest.java
Labels: enhancement

#121 Update get refund api
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailController.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailDAO.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailService.java
  backend/src/main/java/com/ecommerce/backend/orderdetail/OrderDetailServiceImpl.java
  backend/src/test/java/com/ecommerce/backend/unit/orderdetail/OrderDetailServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/user/UserServiceImplTest.java
Labels: update

#127 Update Order Status
  backend/src/main/java/com/ecommerce/backend/order/OrderServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/order/enums/OrderStatus.java
  backend/src/test/java/com/ecommerce/backend/unit/order/OrderServiceImplTest.java
Labels: update

#138 Update Shipper API
  backend/src/main/java/com/ecommerce/backend/order/OrderController.java
  backend/src/main/java/com/ecommerce/backend/order/OrderDAO.java
  backend/src/main/java/com/ecommerce/backend/order/OrderJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/order/OrderRepository.java
  backend/src/main/java/com/ecommerce/backend/order/OrderService.java
  backend/src/main/java/com/ecommerce/backend/order/OrderServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/user/UserController.java
  backend/src/main/java/com/ecommerce/backend/user/UserDAO.java
  backend/src/main/java/com/ecommerce/backend/user/UserJPADataAccessService.java
  backend/src/main/java/com/ecommerce/backend/user/UserRepository.java
  backend/src/main/java/com/ecommerce/backend/user/UserService.java
  backend/src/main/java/com/ecommerce/backend/user/UserServiceImpl.java
  backend/src/main/java/com/ecommerce/backend/user/UserShipperResponse.java
  backend/src/test/java/com/ecommerce/backend/service/auth/AuthenticationServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/category/CategoryServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/order/OrderServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/orderdetail/OrderDetailServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/product/ProductServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/rating/RatingServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/user/UserServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/service/useraddress/UserAddressServiceImplTest.java
  backend/src/test/java/com/ecommerce/backend/util/TestConstants.java
Labels: enhancement

#143 Validate fullname
  frontend/src/pages/Admin/ModalCreateUser/ModalCreateUser.jsx
Labels: enhancement
